from wprocessor import Document, Cursor, Character
print("creating doc = Document()")
doc = Document()
print("doc.filename = test_document")
doc.filename = "test_document"
print("Let's insert hello, letter by letter with LL as bold and a \\n")
doc.insert('h')
doc.insert('e')
doc.insert(Character('L', bold=True))
doc.insert(Character('L', bold=True))
doc.insert('0')
doc.insert('\n')
print("result:")
print(doc.string)
print("Let's insert world with some format")
doc.insert(Character('w', italic=True))
doc.insert(Character('o', italic=True))
doc.insert(Character('r', underline=True))
doc.insert('l')
doc.insert('d')
print(doc.string)
print("doc.cursor.home()")
doc.cursor.home()
print("doc.delete()")
doc.delete()
print("doc.insert('W')")
doc.insert('W')
print(doc.string)
print("doc.characters[0].underline = True ")
doc.characters[0].underline = True
print(doc.string)
