from wprocessor import Document, Cursor
doc = Document()
doc.filename = "test_document"
doc.insert('H')
doc.insert('E')
doc.insert('L')
doc.insert('L')
doc.insert('0')
print("".join(doc.characters))
doc.cursor.back()
doc.delete()
doc.insert('P')
print(''.join(doc.characters))
doc.insert('\n')
doc.insert('w')
doc.insert('o')
doc.insert('r')
doc.insert('l')
doc.insert('d')
doc.cursor.home()
doc.insert('*')
print(''.join(doc.characters))
